### ISSUE TITLE
Wrong name

### ISSUE THREAD

**Issue by Mercury13** [notofonts/znamenny#1]
Should be **Znamenny**

Зна**м**е**нн**ое пение (banner chant) in Russian

And there’s a working colour font in Project Ponomar. They impressed Consortium so much that Znamenny was encoded.

**Comment by Mercury13** [comment]
![image](https://github.com/notofonts/znammeny/assets/10164882/e0949055-4de0-4a25-bebc-5fb1a106b55b)

**Comment by MY1L** [comment]
I agree, just not understand🤔 [@simon](https://github.com/notofonts/znammeny/commit/9583002f3096b18b77d8a8b981c0232ad3dd210c) it is easy enough to copy and paste **Znamenny** Musical Notation https://www.unicode.org/charts/PDF/U1CF00.pdf

**Comment by simoncozens** [comment]
Sorry, yes, this was just a typo on my part.
